project/build.properties
project/plugins.sbt
src/main/scala/treadle/ExecutionEngine.scala
src/main/scala/treadle/ReplConfig.scala
src/main/scala/treadle/TreadleRepl.scala
src/main/scala/treadle/TreadleTester.scala
src/main/scala/treadle/executable/DataStore.scala
src/main/scala/treadle/executable/ExpressionCompiler.scala
src/main/scala/treadle/executable/RenderedExpression.scala
src/test/scala/treadle/RiscVMiniSimpleSpec.scala
src/test/scala/treadle/primops/CatBitsHeadTail.scala
src/test/scala/treadle/primops/EqOpsTester.scala

Riscv mini fix 1

---

src/main/scala/treadle/ExecutionEngine.scala
src/main/scala/treadle/ExternalModule.scala
src/main/scala/treadle/executable/DataStore.scala
src/main/scala/treadle/executable/ExpressionCompiler.scala
src/main/scala/treadle/executable/ExpressionViewBuilder.scala
src/main/scala/treadle/executable/PrintfOp.scala
src/main/scala/treadle/executable/StopOp.scala
src/main/scala/treadle/executable/SymbolTable.scala
src/test/scala/treadle/MultiClockMemorySpec.scala
src/test/scala/treadle/PrintStopSpec.scala
src/test/scala/treadle/RegisterSpec.scala
src/test/scala/treadle/StopBehaviorSpec.scala
src/test/scala/treadle/blackboxes/BlackBoxOutputSpec.scala
src/test/scala/treadle/blackboxes/BlackBoxWithState.scala
src/test/scala/treadle/executable/SymbolTableSpec.scala

Fixed a number of things that enable more chisel3 tests to run 
successfully on treadle.
Major refactor here was new logic for register clock edge detection

Multi clock register refactor

---

src/main/scala/treadle/ExecutionEngine.scala
src/main/scala/treadle/TreadleRepl.scala
src/main/scala/treadle/executable/DataStore.scala
src/main/scala/treadle/executable/DataStorePlugIn.scala
src/test/scala/treadle/ShiftRegisterSpec.scala

Reimplement assignment logging, computation rendering, and vcd logging

---

src/main/scala/treadle/TreadleTester.scala
src/test/scala/treadle/StackSpec.scala

Add expectMemory to TreadleTester

---

src/main/scala/treadle/vcd/VCD.scala
src/test/scala/treadle/vcd/VCDSpec.scala

1 bit signals were not serialized correctly

Implements recent fix to firrtl-interpreter

---

src/test/scala/treadle/chronometry/ChronometrySpec.scala

simple regression test can cause Jenkins CI to fail.

---

src/main/scala/treadle/Driver.scala
src/main/scala/treadle/ExecutionEngine.scala
src/main/scala/treadle/ReplVcdController.scala
src/main/scala/treadle/Timer.scala
src/main/scala/treadle/TreadleRepl.scala
src/main/scala/treadle/VcdReplayTester.scala
src/main/scala/treadle/executable/DataStore.scala
src/main/scala/treadle/executable/DataStorePlugIn.scala
src/main/scala/treadle/executable/ExpressionCompiler.scala
src/main/scala/treadle/executable/Memory.scala
src/main/scala/treadle/executable/Symbol.scala
src/main/scala/treadle/executable/SymbolTable.scala
src/main/scala/treadle/executable/package.scala
src/test/scala/treadle/GCDTester.scala
src/test/scala/treadle/GetIntBreakdownSpec.scala

This is an extensive code cleanup.

---

src/main/scala/treadle/ExecutionEngine.scala
src/main/scala/treadle/TreadleRepl.scala
src/main/scala/treadle/executable/SymbolTable.scala
src/test/scala/treadle/GetIntBreakdownSpec.scala
src/test/scala/treadle/executable/SymbolTableSpec.scala

Uses new firrtl digraph ability to capture node
found in combinational loop detection
Better feedback for user

Combo loop handling improvements

---

src/main/scala/treadle/executable/ClockInfo.scala
src/main/scala/treadle/executable/DataStore.scala
src/main/scala/treadle/executable/RenderedExpression.scala
src/main/scala/treadle/vcd/VCD.scala
src/test/scala/treadle/ExpressionRenderSpec.scala
src/test/scala/treadle/RiscVMiniSimpleSpec.scala

* AssignInt was not calling plugin hook
* Change default clock parameters to be more like verilog
* Necessary improvements to expression rendering
* invert order so last thing you see is signal being rendered
* fix so it does not follow the mux branch not taken
* added tests
* VCD fixes
* memoize ignored wires
* make better elimination of temp signal, keep _GEN_ signals for now

Some general fixes

---

src/main/scala/treadle/TreadleTester.scala
src/main/scala/treadle/executable/IntOps.scala
src/test/scala/treadle/ClockSpec.scala

combinational delay > 0 can cause problems, zero for now
Add test for validif

validif handling is dicey, set to zero for now

---

src/main/scala/treadle/ExecutionEngine.scala
src/main/scala/treadle/ReplVcdController.scala
src/main/scala/treadle/TreadleRepl.scala
src/main/scala/treadle/TreadleTester.scala
src/main/scala/treadle/VcdReplayTester.scala
src/main/scala/treadle/VcdRunner.scala
src/main/scala/treadle/executable/ClockStepper.scala
src/main/scala/treadle/vcd/VCD.scala
src/test/scala/treadle/CombinationalDelaySpec.scala
src/test/scala/treadle/GCDTester.scala
src/test/scala/treadle/vcd/VCDSpec.scala

Refactored VCD replay capabilities.
REPL and VcdReplayTester both use new common class VcdRunner
to implement their VCD replay capabilities.

Replay stuff

---

src/main/scala/treadle/Driver.scala
src/main/scala/treadle/ScalaBlackBox.scala
src/main/scala/treadle/TreadleRepl.scala
src/main/scala/treadle/executable/BlackBoxCycler.scala
src/main/scala/treadle/executable/DataStore.scala
src/main/scala/treadle/executable/ExecutionEngine.scala
src/main/scala/treadle/executable/ExpressionCompiler.scala
src/main/scala/treadle/executable/ExpressionViewBuilder.scala
src/main/scala/treadle/executable/SymbolTable.scala
src/main/scala/treadle/package.scala
src/test/scala/treadle/TestUtils.scala
src/test/scala/treadle/TestUtilsSpec.scala
src/test/scala/treadle/blackboxes/BlackBoxOutputSpec.scala
src/test/scala/treadle/blackboxes/BlackBoxWithState.scala
src/test/scala/treadle/primops/EqOpsTester.scala
src/test/scala/treadle/real/DspRealBlackBox.scala

* Renamed BlackBox stuff to ScalaBlackBox* to avoid conflict with
Interpreter
* Got rid of a few usages of the word interpreter while I am at it.
* Moved scala black box to root treadle package

BlackBox renaming

---

src/main/scala/treadle/executable/DataStore.scala
src/test/scala/treadle/chronometry/ClockCrossingSpec.scala

Subtle ordering problem in runLean code of TriggeredAssign
was the problem.
Updated ClockCrossing firrtl

ClockCrossing test failed when debug and vcd suppressed.

---

src/LICENSE.txt

Missing license file pointed out by @albert-magyar. Thanks

Add LICENSE.txt to src/

---

src/main/scala/treadle/TreadleRepl.scala
src/main/scala/treadle/executable/ExpressionCompiler.scala

- Fixed a couple of unhandled match cases
- Removed a couple of un-referenced vars and defs
- Made depend REPL command work in a useful way

More fixes from Field training Sep 11 2018

---

build.sbt

Make sbt a little better in handling terminal interrupt <cntrl-c>

---

src/main/scala/treadle/TreadleRepl.scala
src/main/scala/treadle/TreadleTester.scala

- forced recognized better across commands
- make show state just dump all wire values

Make output of wire values consistent across commands

---

src/main/scala/treadle/TreadleRepl.scala

Add history number to command prompt.
Add new command *history* to legal commands
history command lists history
accepts regex pattern to narrow things down.
Can execute arbitrary historical command with !<historyNumber>

Add command history numbers

---

src/main/scala/treadle/TreadleRepl.scala
src/main/scala/treadle/executable/Memory.scala

This required to support firrtl [PR 1075](https://github.com/freechipsproject/firrtl/pull/1075)
The depth of the memory has been changed from a Int to a BigInt

Catch large memory size

---

src/main/scala/treadle/executable/SymbolTable.scala
src/test/scala/treadle/PrintStopSpec.scala

Make a local dependency between successive printfs on
a per module basis.
Add test to show that this worked

Attempt to fix ordering of printf statements

---

src/main/scala/treadle/executable/Memory.scala

The `enable` signal on a read port is never used by `treadle` and thus this bug was never discovered. However, I am using it for my symbolic execution extension.
This fixes the fact that instead of creating a enable and a address pipeline the old code would create two address pipelines.
During the course of fixing this I merge the functions for read and write ports into one as their only difference was the latency which can be a function parameter.

Memory: fix en pipeline for read ports

---

src/test/scala/treadle/MemoryUsageSpec.scala

In case you are interested in some more memory tests.
This does not uncover any bugs.

MemoryUsageSpec: test en/mask behavior

---

src/test/scala/treadle/MakeRandomSpec.scala

Count variable was not being reset to zero for each test.

Fix MakeRandomSpec.

---

src/main/scala/treadle/TreadleRepl.scala

In Repl Walltime caused stack trace if file not loaded
help message for walltime was broken

Small cleanup for repl

---

src/main/scala/treadle/TreadleOptions.scala
src/main/scala/treadle/executable/DataStore.scala
src/main/scala/treadle/executable/DataStorePlugIn.scala
src/main/scala/treadle/executable/ExecutionEngine.scala
src/test/scala/treadle/executable/DataStoreSpec.scala

- Datastore plugins now can access previous values
- Add ability to pass in plugins via annotations
- Example test showing a way of doing it.

Enhancements to DataStore plugin support

---

src/main/scala/treadle/executable/SymbolTable.scala

Special case empty string as top module.
Change symbols associated with instances to be InstanceKind

Gives symbol table a mapping between instance names and module names

---

.scala-steward.conf

Is this a reasonable way to trigger things

Make scala-steward run on the first of each month

---

build.sbt
build.sc
src/main/scala/treadle/ScalaBlackBox.scala
src/main/scala/treadle/TreadleOptions.scala
src/main/scala/treadle/TreadleTester.scala
src/main/scala/treadle/executable/DataStorePlugIn.scala
src/main/scala/treadle/executable/Memory.scala
src/main/scala/treadle/executable/RollBackBuffer.scala
src/main/scala/treadle/executable/Snapshotter.scala
src/main/scala/treadle/executable/Symbol.scala
src/main/scala/treadle/package.scala
src/main/scala/treadle/repl/ReplOptions.scala
src/main/scala/treadle/repl/TreadleReplCli.scala
src/main/scala/treadle/stage/TreadleStage.scala
src/main/scala/treadle/stage/phases/PrepareAst.scala
src/main/scala/treadle/utils/RemoveTempWires.scala

Fix doc warnings.
Add fatal warnings flag
Cleanup unused imports
Fixed warning on source not closed

Treadle clean up.

---

README.md
build.sbt
build.sc

Build with: git-clone firrtl https://github.com/freechipsproject/firrtl.git master

Bump SNAPSHOT version.

---

src/main/scala/treadle/executable/Memory.scala

Fix wrong enable shown for memory access
Cleanup unused parameters

Wrong enable signal was shown in expression view of memory access

---

src/test/scala/treadle/MemoryUsageSpec.scala
src/test/scala/treadle/RegOfVecSpec.scala
src/test/scala/treadle/SimpleVendingMachineSpec.scala
src/test/scala/treadle/VecSpec.scala

Several places where a ref declared in a block is referenced outside of that block
Build with: git-clone firrtl https://github.com/freechipsproject/firrtl.git master

Fix problem with hardcoded firrtl

---

build.sc

should be 1.3
Build with: git-clone firrtl https://github.com/freechipsproject/firrtl.git master

version number wrong in build.sc

---

build.sbt

There should be no functional changes
akin to https://github.com/freechipsproject/firrtl/pull/1465

Refactor build.sbt into a more normal style

---

.github/workflows/test.yml
build.sc

 Fix mill and add GitHub CI for mill

---

src/main/scala/treadle/executable/ExpressionCompiler.scala
src/test/scala/treadle/SubtractUIntsNegativeResultSpec.scala

- Adds an AsUInt to subtraction being applied to UInts for Int, Long, and BigInt cases
- Add test demonstrating the correct results for each above case
- Removed unnecessary toSeq

Fixes Issue #291 : UInt Padding Error

---

src/main/scala/treadle/TreadleRepl.scala

The REPL help method is not sorted making it much easier to read.

Sorts repl help mesage

---

build.sbt

Also remove some un-necessary parens in build.sbt

junit is a a fossil, remove it from build.sbt

---

.github/workflows/test.yml
.mergify.yml

Let's see how fast this runs now.

Expose more parallelism in the CI

---

build.sbt
build.sc
project/plugins.sbt

This includes several minor updates suggested by scala steward.

build: update Scala and plugin minor versions

---

src/main/scala/treadle/executable/IntOps.scala
src/main/scala/treadle/executable/LongPrimOps.scala
src/test/scala/treadle/primops/ShlShrDshlDshr.scala

When:
Shifting Int wire by 32 or 64
Shifting Long wire by 64
Both cases now return correct zero value

Fixes DSHR shift problem

---

.github/workflows/test.yml
README.md
build.sbt
build.sc

- Remove from ci, test.yml
- Remove from sbt
- Remove from mill
- Remove from README

Remove Scala 2.11 support

---

build.sbt
project/plugins.sbt

- Add settings to build.sbt
- Add plugin to plugins.sbt

Finish support for BuildInfo

---

src/test/scala/treadle/chronometry/MultiTopLevelClockSpec.scala

- Need better prediction system for when registers
- would transition
- Added tests of various clock relationships
Addresses Issue #258

Make MultiTopLevelClockSpec work

---

src/test/scala/treadle/RegisterSpec.scala
src/test/scala/treadle/executable/SymbolTableSpec.scala

- Not sure how these got here but this
- adds ignores to a couple in RegisterSpec
- specifically looks for expected dependencies in SymbolTableSpec

Fix preset related tests that snuck through

---

src/test/scala/treadle/StopBehaviorSpec.scala

This test would fail before https://github.com/chipsalliance/firrtl/pull/2367 was merged.

test: add test with a submodule to stop behavior spec

---

src/main/scala/treadle/executable/SymbolTable.scala
src/test/scala/treadle/StopBehaviorSpec.scala

Missed commits from stop-fix
Removed verbose mode, and vcd output from test
Cleaned up imports

Removed verbose mode, and vcd output from test
