build.sbt, src/main/scala/treadle/Driver.scala, src/main/scala/treadle/TreadleRepl.scala, src/main/scala/treadle/TreadleTester.scala, src/main/scala/treadle/executable/DataStore.scala, src/main/scala/treadle/executable/DataStorePlugIn.scala, src/main/scala/treadle/executable/SymbolTable.scala, src/test/scala/treadle/blackboxes/BlackBoxOutputSpec.scala, treadle.sh
Add new repl command symbol which can show symbol table entries  …
Fix treadle launch script
Removed unused option clockname
bump build.sbt dependency versions
Do some ground work for moving register latch info into datastore
Do some ground work for making datastore plugins for debugging
Duplicate test removed.
=> Small fixes 1

src/main/scala/treadle/executable/Memory.scala
Register implemented for read latency > 0
had inconsistent names, between parsing and compilation.
=> This fixes a memory reader naming problem

src/main/scala/treadle/ExecutionEngine.scala, src/main/scala/treadle/executable/ExpressionViewBuilder.scala, src/main/scala/treadle/executable/Memory.scala, src/main/scala/treadle/executable/RenderedExpression.scala, src/main/scala/treadle/executable/Scheduler.scala, src/test/scala/treadle/RiscVMiniSimpleSpec.scala
* Add register <= register/in
* Add memory handler to generate expression renders
* Add new Memory method buildMemoryExpressions
* creation is emulation of assigner creation pass
* Add new parameters to rendering to not show values
* Fixed some related scheduler problems
* orphans were not computed before attempting to run static stuff
* orphans were not being removed from combinational assigns
* renderer was improved to use new expression view stuff
=> Render assigners prettier using ExpressionViewRenderer

src/main/scala/treadle/Driver.scala, src/main/scala/treadle/TreadleTester.scala, src/test/scala/treadle/ClockSpec.scala, src/test/scala/treadle/DynamicMemorySearch.scala, src/test/scala/treadle/ExpressionRenderSpec.scala, src/test/scala/treadle/MemoryUsageSpec.scala, src/test/scala/treadle/ModuleInLineSpec.scala, src/test/scala/treadle/RegOfVecSpec.scala, src/test/scala/treadle/RegisterSpec.scala, src/test/scala/treadle/ShiftRegisterSpec.scala, src/test/scala/treadle/StackSpec.scala, src/test/scala/treadle/StopBehaviorSpec.scala, src/test/scala/treadle/blackboxes/BlackBoxWithState.scala, src/test/scala/treadle/chronometry/MultiTopLevelClockSpec.scala, src/test/scala/treadle/primops/CatBitsHeadTail.scala, src/test/scala/treadle/primops/EqOpsTester.scala
the external testing infra-structure
* Rename NoDefaultReset to callResetAtStartup and change the sense of it
* Change the menu options
* Change automatic reset call control
* Multi-stepper should run until reset is cleared
=> TreadleTester should not run reset by default, it might confuse

src/main/scala/treadle/TreadleTester.scala, src/main/scala/treadle/executable/ClockStepper.scala, src/test/scala/treadle/CombinationalDelaySpec.scala
now takes combinational delay which is generally
clock period / 100
If clock period set high enough for this to be non-zero
then the combinational logic can be viewed in vcd
=> Make combinational logic take time

src/main/scala/treadle/Driver.scala, src/main/scala/treadle/ExecutionEngine.scala, src/main/scala/treadle/TreadleTester.scala, src/main/scala/treadle/executable/ClockStepper.scala, src/main/scala/treadle/executable/DataStore.scala, src/main/scala/treadle/executable/DataStorePlugIn.scala, src/main/scala/treadle/executable/RenderedExpression.scala, src/test/scala/treadle/GCDTester.scala, src/test/scala/treadle/RegisterCycleTest.scala
* Added methods to query enabled, enable and disable plug-ins
* Cleaned up render computation, keeps set and it already had engine ref
* Options parser did not pick up symbols to watch from command line
* removed extraneous setVerbose call
* tested that watched symbol was rendered
* Shorten some gcd tests
* Fixed combinational delay not being set above zero with multi-clock
=> Fixed the watch list of symbols that shows their computation

src/main/scala/treadle/ExecutionEngine.scala, src/main/scala/treadle/TreadleTester.scala, src/main/scala/treadle/chronometry/UTC.scala, src/main/scala/treadle/executable/ClockStepper.scala, src/main/scala/treadle/executable/DataStore.scala, src/main/scala/treadle/executable/IntOps.scala, src/main/scala/treadle/executable/RenderedExpression.scala, src/main/scala/treadle/executable/RollBackBuffer.scala, src/main/scala/treadle/executable/Scheduler.scala, src/main/scala/treadle/executable/SymbolTable.scala, src/test/scala/treadle/ExpressionRenderSpec.scala, src/test/scala/treadle/SnapshotSpec.scala, src/test/scala/treadle/VecSpec.scala, src/test/scala/treadle/executable/SymbolTableSpec.scala
* Now, number of rollbacks is per clock
* save state happens before a clock goes high
* DataStore only stores current time values
* history day now in rollback buffers with a manager
* DataStore layout now computed with an allocator so
* arrays don't have to be vars
* snap shot disabled at moment
* RenderedExpressions refactored
* now time based.
* Symbol table now can identify a registers clock name
* Added a test for register rendering
Along the way
* Clock constructor not private anymore
* wall time had to be accessible to engine for rendering purposes
=> Roll back refactor

src/test/scala/treadle/TestUtilsSpec.scala
PR #41 introduced the following compile-time error:
```bash
[info] Compiling 59 Scala sources to .../treadle/target/scala-2.11/test-classes ...
[error] .../treadle/src/test/scala/treadle/TestUtilsSpec.scala:36:29: macro applications do not support named and/or default arguments
[error]       if (count > 18) assert(condition = false)
[error]                             ^
[error] .../treadle/src/test/scala/treadle/TestUtilsSpec.scala:106:29: macro applications do not support named and/or default arguments
[error]       if (count > 18) assert(condition = false)
[error]                             ^
[error] two errors found
[error] (Test / compileIncremental) Compilation failed
```
=> Fix assert() macro failure.

src/main/scala/treadle/TreadleTester.scala, src/main/scala/treadle/chronometry/UTC.scala, src/main/scala/treadle/executable/ClockInfo.scala, src/main/scala/treadle/executable/ClockStepper.scala, src/main/scala/treadle/executable/DataStore.scala, src/main/scala/treadle/executable/ExecutionEngine.scala, src/main/scala/treadle/executable/ExpressionCompiler.scala, src/main/scala/treadle/executable/FindRegisterClocks.scala, src/main/scala/treadle/executable/Scheduler.scala, src/main/scala/treadle/utils/Render.scala, src/test/scala/treadle/CombinationalDelaySpec.scala, src/test/scala/treadle/PrintStopSpec.scala, src/test/scala/treadle/RiscVMiniSimpleSpec.scala, src/test/scala/treadle/blackboxes/BlackBoxWithState.scala, src/test/scala/treadle/chronometry/ClockCrossingSpec.scala
* Attempt to clean up verbose display to make diagnostics easier
* Render.headerBar is attempt to make easier to see blocks in verbose output
* ClockInfo must specify a initialOffset > 0, i.e it is not possible to start with clock set high
* Single step clock improvements
* Has more logic to handle bootstrap clock
* Keep track explicitly of combinational time bumps to better handle down clock
* Reset handling improved (reset may be lowered at times other than clock transitions)
* withClock construct requires special pass to find all clocks that trigger registers
* Fix problem with BlackBoxWithState exposed by this refactor
=> Circuits using withClock were failing

src/main/scala/treadle/Driver.scala, src/main/scala/treadle/ScalaBlackBox.scala, src/main/scala/treadle/executable/BlackBoxCycler.scala, src/main/scala/treadle/executable/Memory.scala, src/test/scala/treadle/DriverSpec.scala, src/test/scala/treadle/RegisterCycleTest.scala, src/test/scala/treadle/blackboxes/BlackBoxOutputSpec.scala, src/test/scala/treadle/blackboxes/BlackBoxWithState.scala
Prior to this a project could not depend on both
For options
- all options preceded by "treadle-"
- all abbreviated options preceded by "t"
For black boxes
- cycle => clockChange
- fullName => completeName
Fixed up problem in Memory.scala where memory pipeline registers did not
have associated clocks defined, which could cause exception in verbose
mode.
=> Makes options and BlackBox support distinct from Interpreter

src/main/scala/treadle/TreadleRepl.scala, src/main/scala/treadle/executable/DataStore.scala, src/main/scala/treadle/executable/ExecutionEngine.scala, src/test/scala/treadle/chronometry/ClockCrossingSpec.scala
- Make it easier to breakpoint in AssignInt
- Enable show-assigns plugin when debug enabled
- Give better error when setting verbose but file not loaded
- Added completions to waitfor command
- Fixed message in waitfor command
- Add inputs and outputs to show command
- fixed wording in help for display command
- Remove CheckChirrtl import for ClockCrossingSpec
=> Bug Fixes from Field training Sep 11 2018

src/main/scala/treadle/executable/DataStore.scala, src/main/scala/treadle/executable/ExecutionEngine.scala, src/main/scala/treadle/executable/Memory.scala, src/main/scala/treadle/executable/SymbolTable.scala, src/test/scala/treadle/MemoryUsageSpec.scala
- Provide an update method for loading memory at offset
- Create memory initializer
- keeps track of memories tagged for loading at start-up
- initializes them, could be re-done by REPL
- symbol table builds list of modules with memories to load
- bit of additional logic to match memories with modules
- add simple test to validate some of this logic
=> Support for loading memories from files at startup

src/main/scala/treadle/TreadleTester.scala, src/main/scala/treadle/chronometry/UTC.scala, src/main/scala/treadle/executable/ExecutionEngine.scala, src/test/scala/treadle/ClockedManuallySpec.scala
- Add advanceTime method to API for precise control of multi-clock DUT
- If signal poked a second time without time or clock advance, evaluate circuit
- Fix scalastyle in engine
- Check transition on triggered assign, and update if up transition
- Add tests for use of advanceTime API
=> Better clock handling

src/main/scala/treadle/executable/FindRegisterClocks.scala, src/test/scala/treadle/chronometry/PrintfOnDerivedClockSpec.scala
- Add logic to find and record the driving clock for printf and stop
- Add scaladoc to the FindRegisterClocks
- Add a test that demonstrates the printf working in this scenario
=> Printfs that used derived clocks were not begin activated

src/test/scala/treadle/vcd/VCDSpec.scala
Don't assume src/test/resources is available. If we're a subproject, the working directory may be higher up in the tree. If we're running out of a Jar, we'll need to fetch this as a real resource.
=> Write resource to file (don't assume src/test/resources/VcdAdder.fir exists)

build.sbt, project/plugins.sbt, src/main/scala/treadle/Regression.scala, src/main/scala/treadle/TreadleRepl.scala, src/main/scala/treadle/TreadleTester.scala, src/main/scala/treadle/executable/BlackBoxCycler.scala, src/main/scala/treadle/executable/ClockStepper.scala, src/main/scala/treadle/executable/DataStore.scala, src/main/scala/treadle/executable/ExecutionEngine.scala, src/main/scala/treadle/executable/ExpressionCompiler.scala, src/main/scala/treadle/executable/PrintfOp.scala, src/main/scala/treadle/executable/RenderedExpression.scala, src/main/scala/treadle/executable/RollBackBuffer.scala, src/main/scala/treadle/executable/Scheduler.scala, src/main/scala/treadle/executable/StopOp.scala, src/main/scala/treadle/executable/SymbolTable.scala, src/main/scala/treadle/executable/Transition.scala, src/main/scala/treadle/utils/RemoveTempWires.scala, src/test/scala/treadle/ClockedManuallySpec.scala, src/test/scala/treadle/GCDTester.scala, src/test/scala/treadle/PrintStopSpec.scala, src/test/scala/treadle/SnapshotSpec.scala, src/test/scala/treadle/VecSpec.scala, src/test/scala/treadle/blackboxes/BlackBoxWithState.scala, src/test/scala/treadle/chronometry/ClockCrossingSpec.scala, src/test/scala/treadle/chronometry/PrintfOnDerivedClockSpec.scala, src/test/scala/treadle/executable/SymbolTableSpec.scala, src/test/scala/treadle/vcd/VCDSpec.scala
This is a large refactor of the execution engine of treadle that accomplishes several tasks
- Makes multi-clock handling work properly even across clock inversions and asClocks
- Fixes printf breaking due to incorrect dependency relations, args might not be calculated before use
- Stop condition could have problem with enable.
- Overall execution is much simpler
- Seems to fix [/freechipsproject/chisel3/issues/993](/freechipsproject/chisel3/issues/993)
It has one major regression issue
- It is 60% of the speed of the current master
- this is due to full circuit evaluation on clock low transition.
=> One pass execution

src/main/scala/treadle/utils/ToLoFirrtl.scala
With freechipsproject/firrtl#994, `Shlw ` node is no more. Long live `Shlw `
=> Remove references to firrtl.PrimOps.Shl - goodbye Shlw

src/main/scala/treadle/executable/ExecutionEngine.scala, src/test/scala/treadle/ClockedManuallySpec.scala
We still support Scala 2.11 which doesn't allow trailing commas.
=> Avoid 2.11 compilation errors with trailing commas.

src/main/scala/treadle/executable/ExecutionEngine.scala, src/main/scala/treadle/executable/PrintfOp.scala, src/main/scala/treadle/executable/RenderedExpression.scala, src/main/scala/treadle/executable/SymbolTable.scala, src/main/scala/treadle/utils/AugmentPrintf.scala, src/test/scala/treadle/ClockedManuallySpec.scala, src/test/scala/treadle/ExpressionRenderSpec.scala, src/test/scala/treadle/PrintStopSpec.scala, src/test/scala/treadle/blackboxes/AsyncResetRegSpec.scala
- Add AugmentPrintf to generate temporary registers between registers
- call that pass at beginning of engine creation
- make printf cache its parsed format string
- fixed display of assigners shown at startup when setVerbose is on
- discovered during debugging
- showing without values should not require rollback buffers
- remove hardcoded sorting of printf to the end of assigner list
- fixed some leftover verbose settings in tests
- add and augment tests of printf
=> Printfs were not printing register values correctly

src/main/scala/treadle/Driver.scala, src/main/scala/treadle/Regression.scala, src/test/scala/treadle/primops/AndOrXor.scala
- Changed default value to 0
- Added another feature to Regression that demonstrates above change
- Added small test to answer question about sign extension of SInt combined with And
=> Set default rollbackBuffers to 0 to improve memory performance

src/main/scala/treadle/ScalaBlackBox.scala, src/main/scala/treadle/executable/SymbolTable.scala, src/test/scala/treadle/RegisterSpec.scala, src/test/scala/treadle/asyncreset/AsyncResetBlackBox.scala, src/test/scala/treadle/blackboxes/AsyncResetRegSpec.scala
- Extend ScalaBlackBox API to add ability to report more dependencies
- SymbolTable uses new method to build better dependency graph
- Added tests for mutually connected registers
- Added similar tests for mutually connected ASyncReset black box registers
=> Fix for problem with black boxes with state interconnected

src/main/scala/treadle/vcd/VCD.scala, src/test/scala/treadle/vcd/VCDSpec.scala
- Make it so values recorded at given time retains only last value
- Change hashCode and equals of Change class to be based on wire id
- Remove change for given wire before adding new one
- Add a test for last value kept during add behavior
- Fixes Issue #90 Incorrect Waveform Output
=> Vcd output broken when poking same wire without clock step. Issue #90

src/main/scala/treadle/utils/BitUtils.scala
- For BitMasks use TrieMap and a more careful get or update scheme
- Reference: [github.com/scala/bug/issues/7943](https://github.com/scala/bug/issues/7943)
How easy is it to produce the error?
=> This is an attempt to prevent concurrency errors in treadle

src/main/scala/treadle/TreadleRepl.scala, src/main/scala/treadle/TreadleTester.scala, src/main/scala/treadle/executable/DataStore.scala, src/main/scala/treadle/executable/DataStorePlugIn.scala, src/main/scala/treadle/executable/Symbol.scala, src/test/scala/treadle/ForceValueSpec.scala
- Forcing implemented via adding forcedValue option field to symbol.
- Assignments to wires checks for this value
- if Some(value) set then sets wire to that instead of ordinary computed value
- Assignment reporting in debug shows forcing information.`
- Added force command
- force alone shows forced wires
- force wire value forces wire to value, stays until explicitly cleared
- force wire clear clears forcing on wire
- TreadleTester API extended
- forceValue forces wire to value until cleared
- clearForceValue clears wire
- Added test that shows TreadleTester forcing use
- Cleaned up imports in TreadleRepl
=> Add ability to force a wire.

src/main/scala/treadle/TreadleRepl.scala, src/main/scala/treadle/executable/ExpressionCompiler.scala, src/main/scala/treadle/executable/ExpressionViewBuilder.scala, src/main/scala/treadle/executable/Symbol.scala, src/main/scala/treadle/executable/SymbolTable.scala, src/test/scala/treadle/NativeAsyncResetSpec.scala
- Add proper references to handle AsyncReset stuff appearing in AST
- Added test that will be used for testing built-in support
- Modify assigners constructed during DefRegister handler
- now muxes register out assignment using treadle operators
- with regular reset, muxes register out depending on clock transition
- with async muxes above with init value depending on reset value
- Expanded NativeAsyncResetSpec
- compares behavior to regular register
- Fix up ExpressionView rendering to match new register assignment methodology
- remove debug from test
=> Built in async reset support

src/main/scala/treadle/TreadleTester.scala, src/main/scala/treadle/stage/TreadleStage.scala, src/main/scala/treadle/stage/phases/PrepareAst.scala
Provide an argument to TreadleTester to specify what form the circuit is in,
Define PrepareAstFromLowFIRRTL object which avoids the "normal" FIRRTL transforms if we're already in LowForm. **NOTE** - trying to refactor this so the two sets of transforms (FIRRTL and Treadle) are composable doesn't appear to work.
Define checkFormTransform method in TreadleCompatibilityPhase which determines which phases are to be run based on the circuit form.
This requires some discussion. Notably, why isn't the CircuitForm a property of the Circuit itself?
=> Quick fix (hack) for Stage/Phase CircuitForm issues.

src/main/scala/treadle/executable/StopOp.scala, src/main/scala/treadle/executable/SymbolTable.scala, src/test/scala/treadle/PrintStopSpec.scala
Make a local dependency between successive stops on
a per module basis.
Stop behavior now checks to see if previous stop has happened.
Add test to show that this worked
=> Attempt to fix ordering of stop statements

src/test/scala/treadle/RegOfVecSpec.scala, src/test/scala/treadle/ShiftRegisterSpec.scala
were based on the incorrect stop ordering.
These have both been fixed so that stop result returned
is recognized to be the first stop statement in the module
that fired.
=> Now that stop ordering is fixed two tests were found that

src/main/scala/treadle/repl/ReplOptions.scala, src/main/scala/treadle/repl/TreadleReplCli.scala, src/main/scala/treadle/stage/TreadleStage.scala
Repl was not running because of two things
- duplicated flag.
- input that somehow not flagged as Low or Chirrtl causes unhandled match
=> Fix REPL not running because of duplicated annotation flag

src/main/scala/treadle/TreadleRepl.scala, src/main/scala/treadle/TreadleTester.scala, src/main/scala/treadle/executable/ClockInfo.scala, src/main/scala/treadle/repl/ReplOptions.scala, src/main/scala/treadle/repl/TreadleReplCli.scala, src/main/scala/treadle/stage/TreadleStage.scala, src/test/scala/treadle/repl/GcdInReplSpec.scala
Treadle can use step or clocks and the wall time can be manipulated
manually. The Repl did not get appropriate commands to utilize
this new capability.
This PR adds it. It includes
- new Repl Command walltime which
- with no args shows current wall time
- with a positive increment will advance the wall time by that ammount
- re-evaluates circuit when advance time occurs
- adds new subcommand clocks to show command
- shows a pretty list of all top level inputs of type clock
- uses a new prettyPrint method of ClockInfo
- Add a test that shows a manually clocked repl session
=> Repl needs advance time

build.sbt
This is currently pointing the `-doc-source-url` at testers and it should be treadle. This will fix the source urls not working on the SNAPSHOT documentation of the website pointing at the wrong GitHub urls (once a new SNAPSHOT is released).
=> Fix incorrect -doc-source-url

src/main/scala/treadle/executable/ExpressionCompiler.scala, src/main/scala/treadle/executable/SymbolTable.scala, src/test/scala/treadle/ClockedManuallySpec.scala
The yosys backend wraps all clock signals in `asClock`.
Not sure why the firrtl type checker allows register clock
signals of type UInt<1> without casting.
=> ExpressionCompiler: make manual clocking work with asClock(clk)

src/main/scala/treadle/executable/Memory.scala
This change only becomes visible if you try to run firrtl without `VerilogMemDelays`.
=> Memory: fix memory pipeline types

treadle.sh
Add -no-colors to treadle.sh start script
=> Ansi escape sequences are a problem when using treadle repl

src/main/scala/treadle/TreadleRepl.scala, src/main/scala/treadle/executable/DataStorePlugIn.scala
Allows adding and removing symbols to watch during circuit eval
Usage
Add symbols with
watch sym1 [sym2 [...]]
Remove them with
watch - sym1 [sym2 [...]]
More generally + and - can be placed anywhere in the
symbol arguments to toggle between adding and deleting
Make symbols to watch in RenderComputations plugin updatable
This will let Repl change it
=> Add new `watch` command to repl

src/main/scala/treadle/stage/phases/PrepareAst.scala, src/test/scala/treadle/PrintStopSpec.scala, src/test/scala/treadle/PrintfCorrectnessSpec.scala
Make registers print at the right time
AugmentPrintf seems to cause problems, remove its call for now
Add test for exact conditions where printf broke in testers2
Reviewed PrintStopSpec, I believe those tests were incorrect
- made it clearer that printf trigger is based on regRegY === 480
- added a count to printf to make it easier to reason about
- conditions tested were logically wrong
- original line 323 wanted rry=479 isZero=0 is480=1
- but is480 could not be true if rry is 479
=> More fixes to printf problems

src/main/scala/treadle/TreadleRepl.scala, utils/bin/treadle
Add treadle script that calls repl's assembly jar
Figured out how to get terminal restored at end of repl session
=> Make it easier to use treadle repl from command line

src/test/scala/treadle/fixedpoint/FixedPointSpec.scala
Problem is that treadle keeps raw firrtl around to run tests on.
- The internal api for set precision is now `setp` for both fixed point an interval
- `bpset` is now `setp`
=> PrimOp changed in Intervals upstreaming

src/main/scala/treadle/TreadleOptions.scala, src/main/scala/treadle/stage/phases/PrepareAst.scala, src/test/scala/treadle/BoreSpec.scala, src/test/scala/treadle/TesterCreationTest.scala
- Makes treadle more robust with various forms of firrtl input
- Add Hint that outside programs can identify their firrtl type to treadle
- Add BoreTest to show BoringUtilsSupport
- Add testers creation test to show starting with different forms
=> Testers2 boring fix

src/main/scala/treadle/stage/phases/SetImplicitOutputInfo.scala
Was picking up name of transform.
Fixed to default to name of circuit
Fixes issue #149
=> Fixed bug in Treadles internal default test directory naming

src/main/scala/treadle/TreadleRepl.scala
Tiny fix, tiny problem
But it came up in use.
=> Fixes incomplete match specification of a datastore plugin in repl

src/main/scala/treadle/TreadleTester.scala, src/test/scala/treadle/StopBehaviorSpec.scala
Allows users of treadle testers to see stop result code.
Generally 0 is a finished ok indicator
Values > 0 indicate error of some sort
Will be used by riscv-mini
=> Provide API for getting stop result in from treadle tester

src/main/scala/treadle/executable/ExpressionCompiler.scala, src/main/scala/treadle/stage/phases/PrepareAst.scala, src/test/scala/treadle/primops/ShlShrDshlDshr.scala
Shl did not handle cases properly when the result crossed over
into the next larger datatype
- Added logic in oneArgOneParam to manage these cases
- This problem does not apply to other primops in this family
- PadWidths removed from TreadleLowFirrtlOptimization
- recommendation of Albert and Adam
- possibly contributing to riscv-mini problems
- Added additional tests to check shift left on data size boundaries
=> Fixes for problem discovered in riscv-mini

src/main/scala/treadle/executable/ExpressionCompiler.scala, src/main/scala/treadle/executable/PrintfOp.scala, src/test/scala/treadle/PrintStopSpec.scala, src/test/scala/treadle/PrintfCorrectnessSpec.scala
- creates implicit columnated output by looking at the width of wire
- adds leading zeros to %x fields
- improved performance by parsing format string only once.
=> Makes treadle printf output formatted more like verilator does

src/main/scala/treadle/executable/ExpressionCompiler.scala
The main fix is to correct an eta expansion notation in shl processing.
Did a minor bit of code cleanup found during fix.
Fix some too long lines etc.
=> Fix code analysis problem introduced with  #154

src/main/scala/treadle/stage/phases/SetImplicitOutputInfo.scala
In some situations the vcd filename's root string is wrong
This fixes it to be same as other names created in test_run_dir
=> The vcd filename can be wrong

src/main/scala/treadle/TreadleOptions.scala, src/main/scala/treadle/executable/ExecutionEngine.scala, src/main/scala/treadle/executable/ExpressionCompiler.scala, src/main/scala/treadle/executable/PrintfOp.scala, src/main/scala/treadle/executable/Scheduler.scala, src/main/scala/treadle/stage/phases/PrepareAst.scala, src/main/scala/treadle/utils/AugmentPrintf.scala, src/test/scala/treadle/PrintStopSpec.scala, src/test/scala/treadle/PrintfCorrectnessSpec.scala, src/test/scala/treadle/PrintfTimingSpec.scala, src/test/scala/treadle/chronometry/PrintfOnDerivedClockSpec.scala
- Was sometimes off a cycle when using a non-constant enable
- Give printf access to testers wall time to make it easier to match printf to vcd
- Make printf format look a bit more like verilator
- Tangled up with this was some diagnostic code
- Add an option PrefixPrintfWithWallTime
- Adds a walltime field to the front of each printf statement
- This really helps with matching up printfs to VCD views
- There remains a problem with the printf when the reset has gone low at the same time as the clock going high.
=> Make printf behavior more closely match verilator

src/main/scala/treadle/executable/ClockInfo.scala
so that simulation starts with clock high.
@johnsbrew reports testing scenarios where it is desirable to start simulation with clock high
See: [chisel-testers/issues/280](https://github.com/freechipsproject/chisel-testers/issues/280)
=> Allows setting the initial phase offset for the clock to zero

src/main/scala/treadle/executable/DataStorePlugIn.scala, src/main/scala/treadle/executable/ExecutionEngine.scala, src/main/scala/treadle/vcd/VCD.scala, src/main/scala/treadle/vcd/diff/VcdComparator.scala, src/test/scala/treadle/vcd/VCDSpec.scala, src/test/scala/treadle/vcd/VcdRoundTripTest.scala
- The VCD writer now uses the engines current vcd  - Instead of using a cached reference that could go stale.
- A VCD read from a file and VCD created by treadle were not using the same lookup convention to find signals
- this has been fixed
- Renamed wires to wiredIdToWire to make it clear how it was used.
- Scopes were not being correctly used during Wire creation in generated VCD.
- VCD now writes itself directly to a file instead of building an entire text image in memory
- This makes it faster, use less memory, it could fail for large files previous to this.
- Added new test that VCD read from file matches the internal one generated by a treadle run
- Added a convenience method `dumpHumanReadable` that prints out a moderately pretty version of a VCD
- this code already existed, just …
=> VCD fixes and improvements

src/main/scala/treadle/executable/Memory.scala, src/main/scala/treadle/executable/SymbolTable.scala, src/main/scala/treadle/stage/phases/PrepareAst.scala, src/test/scala/treadle/ClockSpec.scala, src/test/scala/treadle/MemoryUsageSpec.scala
This will invoke VerilogMemDelays transform that will build
register piplelines, instead of having treadle do it.
This PR changes Memory.scala, to set all latencies to zero
to rely on what was assembled by the VerilogMemDelays.
I'm keeping all the machinery to build these pipelines in Memory.scala since there is a // Todo on VerilogMemDelays in
LowFirrtlOptimization to move it to verilog emitter.
This includes a fix for registers created by Memory to be RegKind instead of WireKind
=> Return to using LowFirrtlOptimization

src/main/scala/treadle/executable/SymbolTable.scala, src/test/scala/treadle/executable/SymbolTableSpec.scala
When found during symbol table processing It displays a combinational loop
(which will just be the first one found, if there are more than one).
The path contains the statements and the @INFO path with symbols on path in red
If a combinational loop is found by CheckComboLoops and you want to see this enhanced display, turn off the combination loop checking with an annotation or command line flag.
DontCheckCombLoopsAnnotation or --no-check-comb-loops
=> Augmented combinational loop report

src/main/scala/treadle/executable/ExpressionViewBuilder.scala, src/main/scala/treadle/executable/RenderedExpression.scala, src/test/scala/treadle/executable/SymbolTableSpec.scala
This contains fixes to complete the rendering of
combinational loops that includes statements with highlighting of symbols along the loop.
Fixes rendering dependencies on rollback buffer sizes which should not matter for combo loops
=> Additional changes for combinational loop reports

src/main/scala/treadle/TreadleOptions.scala, src/main/scala/treadle/executable/ExecutionEngine.scala, src/test/scala/treadle/ShowLoweredFirrtlSpec.scala
This adds SaveFirrtlAtLoadAnnotation as a way to see the lowered firrtl file that will be used by Treadle.
Formerly it would just dump file to stdout when ShowFirrtlAtLoadAnnotation was used.
Adds test to show that this works.
Fixed broken command line adding of ShowFirrtlAtLoadAnnotation
One small typo fix in WriteVcdAnnotation
=> Provide a way to save lowered Firrtl file

src/main/scala/treadle/executable/Memory.scala, src/test/scala/treadle/MemReg.scala, src/test/scala/treadle/MemoryUsageSpec.scala
I am certainly not saying that I've exhaustively looked into the underlying memory implementation, but avoiding the write-latency override to zero that was previously happening in `Memory` makes `MemRegSpec` run successfully.
I deleted the `tester.expectMemory("m", 3, 11)` from `MemoryUsageSpec` because, as far as I can tell, that `expectMemory` should **not** be expected to pass, since it is only reading the undefined initial data from the memory.
These changes are likely what is necessary to make the behavior with `VerilogMemDelays` enabled consistent with that when it is disabled.
=> Fix override of write latency

build.sbt
Since the .scala-steward.conf file doesn't appear to be working (as far as ignoring Berkeley artifacts goes), try the technique mentioned in https://github.com/fthomas/scala-steward/blob/d8e1fd39007fefdb251ec0f07887964cd75a0962/docs/repo-specific-configuration.md
=> Another attempt to have ScalaSteward ignore chisel dependencies.

src/main/scala/treadle/TreadleOptions.scala, src/main/scala/treadle/TreadleRepl.scala, src/main/scala/treadle/TreadleTester.scala, src/main/scala/treadle/executable/DataStorePlugIn.scala, src/main/scala/treadle/executable/ExecutionEngine.scala, src/main/scala/treadle/executable/VcdMemoryLoggingController.scala, src/main/scala/treadle/utils/NumberHelpers.scala, src/test/scala/treadle/MemoryVcdSpec.scala, src/test/scala/treadle/utils/NumberHelpersSpec.scala
Usage
--tr-mem-to-vcd commands
Commands are of the form
```
all.               all indicies for all memories
all:h              all indices for all memories, indices rendered in hex
mem1:all           all indices for memory1
mem1:1,2,3,10-20    mem1 will only have listed indices logged
mem1:0x3,0x10-0x20  mem1 will only have listed indices logged, indices will be rendered in hex
```
tr-mem-to-vcd can appear multiple times on command line to specify other memories
MemoryToVCD annotations can be used instead of command line
- Creates a new VcdMemoryLoggingController that can track what should be logged
- All memories and all indices can be specified
- Specific memories and all indices can be specified
- specific memories and specific ranges of indices can be specified
- indices can be …
=> This adds the ability to log memory changes to vcd output

src/main/scala/treadle/executable/PrintfOp.scala, src/test/scala/treadle/PrintStopSpec.scala, src/test/scala/treadle/PrintfCorrectnessSpec.scala
- Fixes a bug handling escaped percent (%%) in printf format string
- Removes a spurious leading zero when displaying hex format
- Gets the right number of leading zeroes in all cases in hex format
- Adds tests for the above
- Fixes some older tests with incorrect `should`s
- Remove unused parameter in internal function in PrintfOp
=> Increase Fidelity with Verilator Printf

src/main/scala/treadle/TreadleOptions.scala, src/main/scala/treadle/TreadleRepl.scala, src/main/scala/treadle/TreadleTester.scala, src/main/scala/treadle/executable/ExecutionEngine.scala, src/main/scala/treadle/utils/NameBasedRandomNumberGenerator.scala, src/test/scala/treadle/RandomizeCircuit.scala, src/test/scala/treadle/RandomizeCircuitTest.scala, src/test/scala/treadle/executable/SymbolSpec.scala
Seeds are based on register/memory name hashCodes plus a user supplied seed.
This makes randomization deterministic over multiple runs.
Run  RandomizeCircuit and see that happens. Points of interest
Time Event
100  First randomize call
200  Reset
245  Second Randomize call
=> Ability to Randomize Registers and Memory

src/main/scala/treadle/executable/ExecutionEngine.scala
Remove an unused import that is breaking Scaladoc generation.
Since Chisel3 now builds Treadle from source, Treadle needs to generate clean documentation. This is fixing the specific reason that https://app.circleci.com/pipelines/github/freechipsproject/chisel3/1925/workflows/0a062e7b-0b2a-4c44-bedb-7b08b8ef0702/jobs/7188/steps failed. However, a scaladoc block on Treadle should be added to Treadle CI if Treadle is using `-Xfatal-warnings`.
=> Fix unused import

.github/workflows/test.yml
Add a CI step to build the documentation. This should gate future PRs to prevent problems with `-Xfatal-warnings` causing Chisel3 CI to fail.
Note that this is expected to fail without https://github.com/freechipsproject/treadle/pull/224.
=> Add documentation building to CI

src/main/scala/treadle/TreadleOptions.scala
- Several annotations with CLI flags were not registered
- This adds the missing ones: MemoryToVCD, RandomizeAtStartupAnnotation, PrefixPrintfWithWallTime
=> Missing Annotations in CLI list

src/main/scala/treadle/executable/ExecutionEngine.scala, src/main/scala/treadle/executable/Memory.scala, src/test/scala/treadle/MemoryInitializationTest.scala
MemoryArrayInitAnnotation, MemoryRandomInitAnnotation, MemoryScalarInitAnnotation
- Execution engine has new method referenceTargetToSymbols
- Finds all symbols descrived by a reference target
- Add code to initialize memory based on these annotations in Memory.scala
- Add new test function to demonstrate initialization
- Allow for partial paths in reference
- Expanded tests to handle the partial paths
Build with: git-clone firrtl https://github.com/freechipsproject/firrtl.git master
=> Provides support for latest memory initialization annotations

src/main/scala/treadle/stage/phases/PrepareAst.scala
- Switch to using Forms.LowForm
- Include other optimizations from
- LowFormMinimumOptimized
- LowFormOptimized
- without those passes some treadle tests take 25X longer to run
=> Fix problems caused by PadWidths creating Dshlw

src/main/scala/treadle/ScalaBlackBox.scala, src/main/scala/treadle/TreadleTester.scala, src/main/scala/treadle/executable/ExecutionEngine.scala, src/test/scala/treadle/blackboxes/BlackBoxFinishSpec.scala
This calls ScalaBlackBox#finish method allowing
for cleanup or file writing to take place at end of simulation.
=> Implement a finish call for engine

src/main/scala/treadle/Driver.scala, src/main/scala/treadle/TreadleOptions.scala
This adds two options that were added to newer stage phase CLI into the Driver legacy code.
Add deprecation information to treadle CLI for deprecated flags
=> Allows chisel-iotesters to turn on vcd logging of memories

build.sbt
License reference in maven publishing info
now points to apache 2.0
=> Fix license info in build.sbt

build.sbt, build.sc
This brings the major version of Treadle in line with Chisel and FIRRTL.
=> Update version to 1.5-SNAPSHOT, skip 1.4

.mergify.yml
This was probably copied from FIRRTL, but the actual milestone is `1.2.x`, not `1.2.X`
=> Fix milestone in .mergify.yml

.github/workflows/test.yml, project/plugins.sbt
Uses sbt-ci-release for automation
Counterpart of https://github.com/chipsalliance/firrtl/pull/1955
~~**FIXME** For validation, this should push to 1.5-SNAPSHOT. Will make the release flow only happen on pushes before merging.~~ Things work correctly!
=> Automatically publish SNAPSHOTs on pushes

.github/workflows/test.yml, project/plugins.sbt
Uses sbt-ci-release for automation
(cherry picked from commit 0dfdf005dceb24656216096a5469bb0b7e72296f)
Manual backport because Mergify failed to do it 🤷
=> Automatically publish SNAPSHOTs on pushes (#277)

build.sbt
This is now set by sbt-ci-release
=> Remove explicit pom scm from build.sbt

build.sc
- Fixes mill's build.sc to refer to apache license
=> Fix settings so maven reports treadle as apache-2.0

build.sbt, build.sc, src/main/scala/treadle/Regression.scala, src/main/scala/treadle/ScalaBlackBox.scala, src/main/scala/treadle/TreadleRepl.scala, src/main/scala/treadle/blackboxes/EicgWrapper.scala, src/main/scala/treadle/blackboxes/PlusArgReader.scala, src/main/scala/treadle/coverage/package.scala, src/main/scala/treadle/coverage/pass/AddCoverageExpressions.scala, src/main/scala/treadle/executable/BlackBoxCycler.scala, src/main/scala/treadle/executable/DataStore.scala, src/main/scala/treadle/executable/ExpressionCompiler.scala, src/main/scala/treadle/executable/PrintfOp.scala, src/main/scala/treadle/executable/Scheduler.scala, src/main/scala/treadle/executable/StopOp.scala, src/main/scala/treadle/executable/SymbolTable.scala, src/main/scala/treadle/utils/AugmentPrintf.scala, src/main/scala/treadle/utils/NameBasedRandomNumberGenerator.scala, src/main/scala/treadle/vcd/VCD.scala, src/main/scala/treadle/vcd/diff/VcdComparator.scala, src/test/scala/treadle/DynamicMemorySearch.scala
Treadle never needed `-Xsource:2.11`, so I deleted it. It also doesn't need macros-paradise, so I deleted that from the Mill build.
Ironically, this is _almost_ binary compatible for 2.11 and 2.12, but deleting the import in `src/main/scala/treadle/ScalaBlackBox.scala` changes some return types from `collection.Set` to `collection.immutable.Set`. This change could possibly be made in a fully binary incompatible way, but it's not really needed until 1.5 (since Chisel almost certainly will break binary compatibility in adding 2.13). I figured it was better to fix that API because I suspect that using `collection.Set` was unintentional unless @chick tells me otherwise.
=> Add support for Scala 2.13

src/main/scala/treadle/TreadleOptions.scala, src/main/scala/treadle/TreadleTester.scala, src/main/scala/treadle/executable/ExecutionEngine.scala, src/main/scala/treadle/executable/ExpressionCompiler.scala, src/main/scala/treadle/executable/ExpressionViewBuilder.scala, src/main/scala/treadle/executable/SymbolTable.scala, src/main/scala/treadle/executable/VerifyOp.scala, src/main/scala/treadle/stage/phases/HandleFormalStatements.scala, src/main/scala/treadle/utils/CoveragePrettyPrinter.scala, src/test/resources/HasCoverStatements.fir, src/test/scala/treadle/FormalCoverSpec.scala, src/test/scala/treadle/VerificationSpec.scala
This creates a new treadle execution element, `VerifyOp`, that keeps count of all the number of times a coverage statements has seen a rising edge of its clock and how many times the enable and predicate are both true.
At the end of the run the a CSV text file is created in the working directory <circuit-name>.coverage.txt
Additionally a small pretty printer, `CoveragePrettyPrinterMain`, that can take the coverage CSV file and the original firrtl file and produces a text rendering of the firrtl with coverage info added at the end of the lines of coverage statements.
By default those lines are color code as follows
- red means no coverage hits
- cyan means hits but not always
- green means coverage hits equals
Specifically
- Add a couple of hooks to execution engine to help with coverage …
=> Proof of concept for coverage statement counting in Treadle

src/main/scala/treadle/executable/SymbolTable.scala, src/main/scala/treadle/stage/phases/HandleFormalStatements.scala, src/main/scala/treadle/stage/phases/PrepareAst.scala, src/test/resources/HasCoverStatements.fir, src/test/scala/treadle/FormalCoverSpec.scala, src/test/scala/treadle/VerificationSpec.scala
This PR makes `treadle` use the (optional) names of `printf`, `stop` and cover statements as their symbol name instead of auto-generating a name.
Statements that do not have a name (since the name is optional) are automatically named through the `EnsureNamedStatements` pass from firrtl.
=> Use Statement Names from Firrtl

build.sbt, build.sc
=> build: remove scalacheck dependency

build.sbt, build.sc
These are pulled in via firrtl anyways and specifying
them explicitly just leads to potential version conflicts.
=> build: remove explicit dependencies on scopt and json libraries

src/main/scala/treadle/executable/ExpressionCompiler.scala, src/main/scala/treadle/executable/ExpressionViewBuilder.scala, src/main/scala/treadle/executable/SymbolTable.scala, src/test/resources/CoverageTestModule.fir, src/test/scala/treadle/FormalCoverSpec.scala
Previously the `symbolTable.verifyToVerifyInfo` HashMap would map a firrtl cover statement to its treadle Symbol.
However, since a module can be instantiated more than once, this lead to aliasing problems.
We now use the unique symbol name to index into this hash table.
=> cover: fix aliasing of submodule cover statements

README.md
`import chisel._` led to `not found: object chisel` error
=> Fix chisel3 import in README example

src/main/scala/treadle/executable/IntOps.scala, src/main/scala/treadle/executable/LongPrimOps.scala, src/test/scala/treadle/PrintStopSpec.scala, src/test/scala/treadle/primops/ShlShrDshlDshr.scala
This is an manual backport of pull request #322
When:
Shifting Int wire by 32 or 64
Shifting Long wire by 64
Both cases now return correct zero value
Also contains fix of PrintStopSpec passing multi-bit enable to stop
=> Backport pr322

src/main/scala/treadle/TreadleTester.scala, src/test/scala/treadle/MemoryUsageSpec.scala
Helpful to see what memory index was being called when a failure occurs
Addresses Issue #232
=> expectMemory now shows index when error occurs

src/main/scala/treadle/TreadleTester.scala, src/main/scala/treadle/executable/ExecutionEngine.scala, src/main/scala/treadle/executable/ExpressionCompiler.scala, src/main/scala/treadle/executable/StopOp.scala, src/main/scala/treadle/executable/TreadleException.scala, src/test/scala/treadle/PrintStopSpec.scala, src/test/scala/treadle/StopBehaviorSpec.scala, src/test/scala/treadle/VerificationSpec.scala
- When stop happens during circuit evaluation
- Create and `StopException`
- Save it in the engine
- At end of circuit evaluation
- Check for saved `StopException`
- Throw it
- Create richer `StopException`
- Includes `stopValue`, `stopName`, `info`
- These can be used for richer analysis and reporting
- Fix up some tests
- Fix up randomization implementation
- Exposed by problem when running `RandomizeCircuitTest`
=> Cleans up `Stop` handling in Treadle

src/main/scala/treadle/executable/Transition.scala, src/main/scala/treadle/utils/AugmentPrintf.scala, src/test/resources/ToggleCoverage.fir, src/test/scala/treadle/CoverageIssue.scala, src/test/scala/treadle/FormalCoverSpec.scala, src/test/scala/treadle/VerificationSpec.scala
Fix coverage tests view of registers
- Like printf, verification (cover) statements need to use previous values of enable and predicate and arguments
- Add verification statement to AugmentPrintf transform
- For debugging show current value of register (still notes when register was not changed because of clock transition)
=> Fix verification register handling

.scalafmt.conf, project/plugins.sbt
Update scalafmt sbt plugin
- 2.42 -> 2.4.3
- change references to danglingParentheses options to stop deprecation-warning
=> Update scalafmt sbt plugin

src/main/scala/treadle/TreadleTester.scala, src/test/scala/treadle/ClockSpec.scala
This adds an attempt for treadle to find a top level clock with a name other than "clock"
by searching for one top level input with name clock.
This generally should only effect direct use of `TreadleTester` as most testing frameworks manage this on their own.
A test to demonstrate this change working
=> Treadle can find clock with some other name

src/main/scala/treadle/TreadleTester.scala, src/main/scala/treadle/executable/ExecutionEngine.scala
This avoids many spurious warnings.
=> TreadleTester: better findTopLevelClocks method

src/main/scala/treadle/executable/ExpressionCompiler.scala, src/main/scala/treadle/executable/ExpressionViewBuilder.scala, src/main/scala/treadle/executable/SymbolTable.scala, src/test/scala/treadle/StopBehaviorSpec.scala
Fixes stops hiding other stops
The communication between symbol table assembly and expression compiling used a case class as key
Changed the key to be a string representing the full pathname of the stop.
This seems to fix the problem.
=> Fixes stops hiding other stops

src/main/scala/treadle/vcd/VCD.scala, src/test/scala/treadle/vcd/VCDSpec.scala
This matches the default verilator behavior.
=> vcd: exclude all signals that start with `_` by default

project/build.properties
Avoids any possibility of [CVE-2021-44228](https://github.com/advisories/GHSA-jfh8-c2jp-5v3q), although given this is Zinc's own logging, it would be pretty insane to see how that attack vector would manifest here.
=> Bump to sbt 1.5.6

src/main/scala/treadle/executable/DataStore.scala, src/test/resources/CircularPointerFifo.lo.fir, src/test/scala/treadle/MemoryUsageSpec.scala
This seems to be a copy-paste error. The `Long` and `BigInt` versions already correctly implemented the wrapping.
=> DataStore: ignore out of bounds writes to memory
